// ==================== ECOLOGY DATA ====================
// Biome definitions, target map, biome profiles, atmosphere storage,
// and landmark placement data.  All world-generation and terrain data.
// Split from constants.js — no imports from project modules.

// ==================== BIOME PALETTES ====================

export const BIOME = {
  // --- Photosynthetic biomes ---
  // Native Clade-A vision: lifted brightness, rich warm-spectrum separation.

  // Plains: OLIVE-brown — warmer, more yellow-shifted than forest.
  // Green channel leads slightly over forest; firmly warm, not cool.
  plains:    {bg:'#342818', fg:'#7a4c38', mid:'#583a28', tint:null},

  // Forest: RED-brown — dominant red channel, deep maroon-red canopy.
  // Clearly redder than plains at a glance.
  forest:    {bg:'#2e160e', fg:'#6a2c24', mid:'#4a2018', tint:'#6a2c24'},

  // --- Mineral-depleted zone: pale, desaturated, washed-out gray ---
  // The "dead zone" — muted and gray against the rich living biomes.
  desert:    {bg:'#383636', fg:'#bab6b2', mid:'#868280', tint:'#a09c98'},

  // --- Rock/mountain: warm earthy stone ---
  rock:      {bg:'#3a3228', fg:'#a89a84', mid:'#786c58', tint:'#968a76'},

  // --- Water: amber-tinted, translucent, readable ---
  // Shallows warm and inviting; deep darker but still clearly amber.
  water:     {bg:'#302a1c', fg:'#b09868', mid:'#6e5c3c', tint:null},
  deep:      {bg:'#221c14', fg:'#786a50', mid:'#443a28', tint:null},

  // --- Geothermal: lava stays hot ---
  lava:      {bg:'#3e1a10', fg:'#e08060', mid:'#b85030', tint:'#d06040'},

  // --- Stone (boulders, stairs, structural) ---
  stone:     {bg:'#302c24', fg:'#a09686', mid:'#665e50', tint:'#a89886'},

  // --- Underground: warm amber-brown, well-lit by native eyes ---
  // Geothermally active ecosystem — not a dark dungeon.
  cave:      {bg:'#261e18', fg:'#8e8474', mid:'#584e40', tint:'#8e7860'},
  uwater:    {bg:'#1c2214', fg:'#748c5c', mid:'#404a34', tint:'#7a9a64'},

  // --- Built structures: warm amber lamplight ---
  town:      {bg:'#302418', fg:'#d4be98', mid:'#9a8060', tint:null},
  castle:    {bg:'#2e2a28', fg:'#beb8b0', mid:'#746c60', tint:null},
  road:      {bg:'#362c20', fg:'#987c58', mid:'#6a5438', tint:null},
  wood_floor:{bg:'#2c2010', fg:'#8e6c44', mid:'#604828', tint:null},

  // --- Chemotrophic biomes: manganese PURPLE — most visually distinct ---
  // Cool purple against all the warm reds and browns makes it pop.
  mushroom:  {bg:'#241c30', fg:'#806898', mid:'#583c68', tint:'#70587e'},
  mushforest:{bg:'#261e32', fg:'#866c90', mid:'#5a3e6c', tint:'#70587e'},

  // --- Crops: muted amber ---
  wheat:     {bg:'#382e18', fg:'#aa8c48', mid:'#7a6438', tint:null},

  // --- New / updated palettes ---
  beach:     {bg:'#403628', fg:'#a89474', mid:'#786a50', tint:'#8e7c58'},
  ruin:      {bg:'#2a2624', fg:'#6e645c', mid:'#524e48', tint:'#645c58'},
  void:      {bg:'#000000', fg:'#000000', mid:'#000000', tint:null},
  cave_wall: {bg:'#1a1614', fg:'#342e28', mid:'#262220', tint:null},
  cave_rock: {bg:'#181816', fg:'#2c2a28', mid:'#201e1c', tint:null},

  // --- Wetland: AMBER-brown, warmest, most golden biome ---
  // Mineral-rich water + organic material = rich golden tint.
  mud:       {bg:'#2c2010', fg:'#7a5c28', mid:'#54401c', tint:'#664820'},

  // --- Fungal ground: purple-dark chemotrophic mat ---
  fungal_grass:{bg:'#221c2e', fg:'#6c5c88', mid:'#4c3e5e', tint:'#5c4c6e'},

  // --- Bare earth ---
  dirt:      {bg:'#362a14', fg:'#7e6840', mid:'#5e482c', tint:null},
  hut_wall:  {bg:'#2c2010', fg:'#8e6c44', mid:'#604828', tint:null},
};

// ==================== BIOME TARGET MAP ====================
// BIOME_GRID_W × BIOME_GRID_H low-resolution grid — the single source of truth
// for biome placement.  Each cell names the biome that owns that region.
// Surface generation reads this directly; no intermediate atmosphere fields
// are needed.
// Rows run north (0) → south (BIOME_GRID_H-1),
// columns west (0) → east (BIOME_GRID_W-1).
//
// The "mountain" biome has been removed.  All former mountain cells are now
// "rock", which uses walkable rock ground with boulder/outcrop cover.
// The former "water" biome has been split into "ocean" (deep open water)
// and "shallows" (coastal transition).  "stone" → "rock", "mushroom" →
// "fungal", "mud" → "wetland".
//
// Each cell is { biome, density, blend }.  `density` (0.0–1.0) controls cover
// intensity — e.g. tree probability in forests — without changing biome
// identity.  `blend` (0.0–1.0) controls how far this cell's ground palette
// reaches into neighboring cells and the noise wavelength in the transition
// zone.  Both values are bilinearly interpolated across the map.
// Density and blend are independent parameters.
function B(biome, density, blend) { return { biome, density, blend: blend !== undefined ? blend : 0.5 }; }

// BIOME_TARGET — 16 x 16
// Generated by Biome Map Editor
//
// The "mountain" biome has been removed.  All former mountain cells are now
// "rock", which uses walkable rock ground with boulder/outcrop cover.
// The former "water" biome has been split into "ocean" (deep open water)
// and "shallows" (coastal transition).  "stone" → "rock", "mushroom" →
// "fungal", "mud" → "wetland".

export const BIOME_TARGET = [
  [B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2)],
  [B('shallows',1.0,0.2), B('wetland',1.0,0.9), B('shallows',1.0,0.8), B('wetland',1.0,0.9), B('shallows',1.0,0.8), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2)],
  [B('shallows',1.0,0.2), B('wetland',1.0,0.9), B('wetland',1.0,0.9), B('wetland',1.0,0.2), B('wetland',1.0,0.9), B('shallows',1.0,0.8), B('forest',0.9,0.7), B('shallows',1.0,0.8), B('forest',0.9,0.7), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('beach',0.7,0.3), B('beach',0.7,0.3), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('ocean',1.0,0.2)],
  [B('shallows',1.0,0.2), B('wetland',1.0,0.9), B('wetland',1.0,0.9), B('wetland',1.0,0.2), B('wetland',1.0,0.2), B('forest',1.0,0.2), B('forest',1.0,0.2), B('forest',1.0,0.2), B('forest',1.0,0.2), B('shallows',1.0,0.2), B('beach',0.7,0.3), B('beach',0.7,0.3), B('beach',0.7,0.3), B('beach',0.7,0.3), B('shallows',1.0,0.2), B('ocean',1.0,0.2)],
  [B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('wetland',1.0,0.9), B('wetland',1.0,0.2), B('forest',0.3,0.4), B('shallows',1.0,0.9), B('forest',0.9,0.5), B('shallows',1.0,0.7), B('forest',0.9,0.5), B('forest',1.0,0.2), B('plains',0.7,0.2), B('beach',0.7,0.3), B('beach',0.7,0.3), B('beach',0.7,0.3), B('shallows',1.0,0.2), B('ocean',1.0,0.2)],
  [B('ocean',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.8), B('plains',1.0,0.2), B('wetland',1.0,0.2), B('wetland',1.0,0.2), B('wetland',1.0,0.9), B('forest',0.7,0.9), B('forest',0.7,0.9), B('forest',0.7,0.9), B('forest',0.3,0.9), B('plains',0.3,0.2), B('plains',0.2,0.2), B('beach',0.7,0.3), B('shallows',1.0,0.2), B('ocean',1.0,0.2)],
  [B('ocean',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.8), B('forest',0.1,0.2), B('shallows',1.0,0.7), B('wetland',1.0,0.9), B('forest',0.1,0.9), B('wetland',1.0,1.0), B('plains',1.0,0.7), B('shallows',1.0,0.4), B('forest',0.7,0.9), B('shallows',1.0,0.2), B('plains',0.6,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('ocean',1.0,0.2)],
  [B('ocean',1.0,0.2), B('shallows',1.0,0.2), B('forest',0.4,0.2), B('forest',0.3,0.2), B('forest',0.9,0.5), B('forest',0.7,0.9), B('wetland',1.0,1.0), B('plains',1.0,0.2), B('plains',1.0,0.2), B('plains',1.0,0.7), B('forest',0.7,0.9), B('shallows',1.0,0.5), B('plains',1.0,0.2), B('shallows',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2)],
  [B('ocean',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('forest',0.6,0.2), B('wetland',1.0,0.9), B('forest',0.7,0.9), B('shallows',1.0,0.7), B('plains',1.0,0.2), B('forest',0.1,1.0), B('plains',1.0,0.7), B('forest',0.7,0.9), B('wetland',1.0,0.9), B('plains',1.0,0.2), B('shallows',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2)],
  [B('ocean',1.0,0.2), B('shallows',1.0,0.2), B('forest',0.8,0.7), B('forest',0.8,0.7), B('shallows',1.0,0.7), B('forest',0.7,0.9), B('plains',1.0,0.2), B('plains',1.0,0.7), B('plains',1.0,0.7), B('shallows',1.0,0.9), B('plains',1.0,0.2), B('plains',1.0,0.2), B('fungal',1.0,0.3), B('shallows',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2)],
  [B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('forest',0.7,0.9), B('forest',0.3,0.5), B('shallows',1.0,0.9), B('forest',0.7,0.9), B('forest',0.7,0.9), B('forest',0.7,0.9), B('wetland',1.0,0.9), B('wetland',1.0,0.9), B('fungal',1.0,0.8), B('shallows',1.0,0.7), B('shallows',1.0,0.0), B('shallows',1.0,0.0), B('shallows',1.0,0.2)],
  [B('shallows',1.0,0.2), B('forest',0.7,0.9), B('forest',0.7,0.9), B('forest',1.0,0.9), B('forest',0.7,0.9), B('forest',0.3,0.5), B('forest',0.3,0.5), B('forest',0.9,0.5), B('forest',0.9,0.5), B('shallows',1.0,0.3), B('fungal',1.0,0.8), B('fungal',1.0,0.3), B('fungal',1.0,0.3), B('fungal',1.0,0.3), B('shallows',1.0,0.2), B('shallows',1.0,0.2)],
  [B('shallows',1.0,0.2), B('shallows',1.0,0.7), B('forest',0.7,0.9), B('shallows',1.0,0.9), B('forest',0.7,0.3), B('forest',0.6,0.3), B('forest',0.3,0.3), B('forest',1.0,0.2), B('shallows',1.0,0.9), B('fungal',1.0,0.9), B('shallows',1.0,0.9), B('fungal',1.0,0.3), B('fungal',1.0,0.3), B('fungal',1.0,0.3), B('fungal',1.0,0.3), B('shallows',1.0,0.9)],
  [B('ocean',1.0,0.2), B('shallows',1.0,0.7), B('shallows',1.0,0.2), B('forest',0.7,0.9), B('shallows',1.0,0.9), B('forest',0.7,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('fungal',1.0,0.9), B('shallows',1.0,0.7), B('fungal',1.0,0.3), B('fungal',1.0,0.3), B('fungal',1.0,0.6), B('fungal',0.7,0.6), B('shallows',1.0,0.2)],
  [B('ocean',1.0,0.2), B('shallows',1.0,0.7), B('forest',0.7,0.9), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('fungal',1.0,0.3), B('fungal',1.0,0.3), B('fungal',0.7,0.3), B('fungal',0.7,0.6), B('fungal',0.7,0.6), B('shallows',1.0,0.7)],
  [B('ocean',1.0,0.2), B('shallows',1.0,0.7), B('shallows',1.0,0.7), B('shallows',1.0,0.7), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('ocean',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.2), B('shallows',1.0,0.7), B('shallows',1.0,0.7)]
];

// ==================== BIOME PROFILES ====================
// Self-contained definition for every biome that appears on the target map.
// Adding a new biome = adding one entry here + placing it on BIOME_TARGET.
//
// Fields:
//   groundPalette — { terrainType: weight } map of weighted ground types.
//                   Weights should sum to 1.0.  During generation, palettes
//                   from blended biomes are interpolated by distance, and
//                   a noise field selects the ground type per tile.
//   ground        — legacy: dominant ground type (highest palette weight).
//                   Kept for downstream code that reads a single ground type.
//   covers        — array of { type, chance } objects.  Each is rolled
//                   independently per tile; first hit wins.
//   lakeChance    — probability of a coherent water pocket (noise-gated)
//   palette       — key into the BIOME palette table (for rendering)
//   derived       — { moisture, elevation, fungal } values written to the
//                   atmosphere fields so downstream systems can query them.
//                   These do NOT drive biome selection.

export const BIOME_PROFILES = {
  plains: {
    groundPalette: { 0: 0.70, 57: 0.08, 55: 0.12, 4: 0.05 },   // grass 70%, dirt 8%, mud 12%, water 5% — damp patches & puddles
    ground: 0,                                // legacy: dominant ground (T.GRASS)
    scatter: 0.10,                            // occasional dirt tiles, mostly grass
    noiseAmp: 0.30,
    covers: [
      { type: 1, chance: 0.08 },              // sparse trees
    ],
    coverScale: (coverType, density) => {
      if (coverType === 1) return 0.005 + density * 0.025;
      return null;
    },
    lakeChance: 0.015,
    palette: 'plains',
    derived: { moisture: 0.35, elevation: 0.30, fungal: 0 },
  },
  forest: {
    groundPalette: { 0: 0.62, 57: 0.08, 55: 0.18, 4: 0.07 },      // grass 62%, dirt 8%, mud 18%, water 7% — saturated forest floor
    ground: 0,
    scatter: 0.08,                             // mostly grass, rare dirt
    noiseAmp: 0.30,
    covers: [
      { type: 1, chance: 0.70 },              // dense canopy
    ],
    coverScale: (coverType, density) => {
      if (coverType === 1) return 0.03 + density * 0.89;
      return null;
    },
    lakeChance: 0.008,
    palette: 'forest',
    derived: { moisture: 0.58, elevation: 0.38, fungal: 0 },
  },
  desert: {
    groundPalette: { 2: 1.0 },                // sand 100%
    ground: 2,
    scatter: 0.03,                             // near-solid sand
    noiseAmp: 0.25,
    covers: [],
    coverScale: (coverType, density) => {
      if (coverType === 1) return 0;
      return null;
    },
    lakeChance: 0,
    palette: 'desert',
    derived: { moisture: 0.10, elevation: 0.40, fungal: 0 },
  },
  rock: {
    groundPalette: { 3: 1.0 },                // rock 100%
    ground: 3,
    scatter: 0.05,                             // solid rock
    noiseAmp: 0.25,
    covers: [
      { type: 53, chance: 0.10 },             // boulders
      { type: 54, chance: 0.08 },             // rock outcrops
    ],
    coverScale: (coverType, density) => {
      if (coverType === 1) return 0;
      return null;
    },
    lakeChance: 0,
    palette: 'rock',
    derived: { moisture: 0.18, elevation: 0.80, fungal: 0 },
  },
  ocean: {
    groundPalette: { 5: 0.7, 4: 0.3 },       // deep_water 70%, water 30%
    ground: 5,
    scatter: 0.05,                             // mostly solid deep/shallow mix
    noiseAmp: 0.25,
    covers: [],
    coverScale: (coverType, density) => {
      if (coverType === 1) return 0;
      return null;
    },
    lakeChance: 0,
    palette: 'water',
    derived: { moisture: 0.90, elevation: 0.10, fungal: 0 },
  },
  shallows: {
    groundPalette: { 4: 0.50, 55: 0.20, 0: 0.15, 2: 0.10, 7: 0.05 }, // water 50%, mud 20%, grass 15%, sand 10%, beach 5% — tidal gradient
    ground: 4,
    scatter: 0.15,                             // moderate intermixing at coast
    noiseAmp: 0.30,
    covers: [],
    coverScale: (coverType, density) => {
      if (coverType === 1) return 0;
      return null;
    },
    lakeChance: 0,
    palette: 'water',
    derived: { moisture: 0.80, elevation: 0.15, fungal: 0 },
  },
  wetland: {
    groundPalette: { 55: 0.35, 4: 0.35, 0: 0.25, 57: 0.05 }, // mud 35%, water 35%, grass 25%, dirt 5% — slightly wetter
    ground: 55,
    scatter: 0.35,                             // heavy speckling — puddles everywhere
    noiseAmp: 0.20,
    covers: [],
    coverScale: (coverType, density) => {
      if (coverType === 1) return 0.01 + density * 0.04;
      return null;
    },
    lakeChance: 0.02,
    palette: 'mud',
    derived: { moisture: 0.70, elevation: 0.25, fungal: 0 },
  },
  fungal: {
    groundPalette: { 56: 0.75, 55: 0.15, 4: 0.05 },     // fungal_grass 75%, mud 15%, water 5% — waterlogged mineral flats
    ground: 56,
    scatter: 0.12,                             // some mud speckling in fungal ground
    noiseAmp: 0.25,
    covers: [
      { type: 8, chance: 0.80 },              // mushroom forest
    ],
    coverScale: (coverType, density) => {
      if (coverType === 1) return 0;
      return null;
    },
    lakeChance: 0,
    palette: 'fungal_grass',
    derived: { moisture: 0.45, elevation: 0.35, fungal: 0.65 },
  },
  beach: {
    groundPalette: { 7: 0.80, 2: 0.12, 57: 0.08 }, // beach 80%, sand 12%, dirt 8%
    ground: 7,
    scatter: 0.10,                             // occasional sand/dirt patches
    noiseAmp: 0.25,
    covers: [
      { type: 53, chance: 0.03 },              // sparse boulders
      { type: 54, chance: 0.04 },              // occasional rock outcrops
    ],
    coverScale: (coverType, density) => {
      if (coverType === 1) return 0;           // no forest from cover blending
      return null;
    },
    lakeChance: 0,
    palette: 'beach',
    derived: { moisture: 0.75, elevation: 0.12, fungal: 0 },
  },
};

// ==================== BLEND TUNING ====================
// Per-cell `blend` parameter (0.0–1.0) on the BIOME_TARGET map controls
// transition width and noise coherence at biome boundaries.
//   blend: 0.0  → near-hard edge, 1–2 tiles of transition
//   blend: 0.5  → moderate transition, several tiles of gradient
//   blend: 1.0  → maximum blending, full smooth gradient between cell centers
// Each cell controls its OWN side of the boundary — asymmetric transitions
// emerge naturally when neighboring cells have different blend values.
// Noise wavelength within the transition zone scales with blend:
//   high blend → large smooth patches,  low blend → small sharp patches.
// The old global BLEND_WIDTH constant has been replaced by this system.

// ==================== ATMOSPHERE FIELD STORAGE ====================
// Populated by surface-gen with values *derived from* the biome profile,
// NOT used to select biomes.  Downstream systems (fire spread, creature
// comfort, etc.) may query these; for now they are inert.
// Structure: { moisture: Float32Array, elevation: Float32Array,
//              fungal: Float32Array, w: number, h: number }
// Access pattern: fields.moisture[y * w + x]
export const ATMOSPHERE = {};

// Helper: query atmosphere value at a tile coordinate
export function getAtmosphere(x, y) {
  const a = ATMOSPHERE;
  if (!a.w) return { moisture: 0.5, elevation: 0.5, fungal: 0 };
  const cx = Math.max(0, Math.min(a.w - 1, Math.floor(x)));
  const cy = Math.max(0, Math.min(a.h - 1, Math.floor(y)));
  const idx = cy * a.w + cx;
  return {
    moisture:  a.moisture  ? a.moisture[idx]  : 0.5,
    elevation: a.elevation ? a.elevation[idx] : 0.5,
    fungal:    a.fungal    ? a.fungal[idx]    : 0,
  };
}

// ==================== LANDMARKS ====================
// Structures placed at biome-target-map scale.  Each entry defines:
//   type  — identifier string matching a generator in LANDMARK_GENERATORS
//   cells — array of target map coordinates this landmark occupies
// During surface generation the landmark system calculates a world-tile
// bounding box from the cells, clears cover in that footprint, and calls
// the generator to stamp its tiles.
export const LANDMARKS = [
  // DISABLED — legacy content
  // {
  //   type: 'village',
  //   cells: [
  //     { x: 4, y: 4 }, { x: 5, y: 4 },
  //     { x: 4, y: 5 }, { x: 5, y: 5 },
  //   ],
  // },
];

